from config import settings
from langchain_huggingface import HuggingFaceEmbeddings


huggingface_embeding_model = settings.HUGGINGFACE_EMBEDDING_MODEL
embedding = HuggingFaceEmbeddings(model_name=huggingface_embeding_model)